name: KiCad Diff Delete

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  pull_request:
    paths:
      - pcb/**
    types:
      - closed

jobs:
  kiri-delete:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          repository: jniebuhr/kiri-github-action
          path: ./kiri-action
      - name: Kiri
        uses: ./kiri-action
