name: KiCad Diff Delete

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  pull_request:
    paths:
      - pcb/**
    types:
      - closed

jobs:
  kiri-delete:
    runs-on: ubuntu-latest
    steps:
      - name: Kiri
        uses: usa-reddragon/kiri-github-action@v1
