name: KiCad Pull Request Diff

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - pcb/**
    types:
      - opened
      - synchronize

jobs:
  kiri-diff:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v3
        with:
          repository: jniebuhr/kiri-github-action
          path: ./kiri-action
      - name: Kiri
        uses: ./kiri-action
        with:
          project-file: pcb/Gaggimate.kicad_pro
